version: "3.3"
services:
  postgres:
    container_name: WeatherApp
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: weatherapp
      POSTGRES_PASSWORD: weatherapp
      POSTGRES_DB: weatherapp
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_NAME: weatherapp
      DB_USERNAME: weatherapp
      DB_PASSWORD: weatherapp

volumes:
  postgres: