version: '3'

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:12.15
    env_file:
      - .env
