version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: weather_app_db
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/app
      - ~/.m2/repository:/root/.m2/repository
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/weather_app_db
      - spring.datasource.username=root
      - spring.datasource.password=test@123


volumes:
  db_data: