spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/weatherapp;DB_CLOSE_DELAY=-1
    username: weatherapp
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update