spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update