version: "3.8"
services:
  pgsql:
    image: postgres:14.5
    container_name: pgslq145
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weatherdb
      - PGDATA=/var/lib/postgresql/data/pgsqlv145/
    ports:
      - 5432:5432
    volumes:
      - ~/weatherdockerdata/postgresql/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql